#!/usr/bin/env python3
"""
Unicode Glyph Harvester
Dumps all printable Unicode characters organized by category
"""

import unicodedata
import sys

def is_printable_glyph(char):
    """Check if character is a visible glyph (not control/whitespace)"""
    category = unicodedata.category(char)
    # Exclude control chars (Cc), format chars (Cf), surrogates (Cs),
    # private use (Co), not assigned (Cn), whitespace
    excluded = {'Cc', 'Cf', 'Cs', 'Co', 'Cn', 'Zs', 'Zl', 'Zp'}
    return category not in excluded and char.isprintable()

def harvest_unicode_glyphs():
    """Extract all printable glyphs from Unicode space"""
    glyphs_by_category = {}

    # Iterate through Unicode code points (0x0000 to 0x10FFFF)
    # Focus on BMP (Basic Multilingual Plane) first: 0x0000-0xFFFF
    # Plus selected supplementary planes
    ranges = [
        (0x0000, 0xFFFF, "Basic Multilingual Plane"),
        (0x10000, 0x1FFFF, "Supplementary Multilingual Plane"),
        (0x20000, 0x2FFFF, "Supplementary Ideographic Plane"),
    ]

    total = 0
    for start, end, plane_name in ranges:
        print(f"Scanning {plane_name}...", file=sys.stderr)
        for codepoint in range(start, end + 1):
            try:
                char = chr(codepoint)
                if is_printable_glyph(char):
                    category = unicodedata.category(char)
                    if category not in glyphs_by_category:
                        glyphs_by_category[category] = []
                    glyphs_by_category[category].append((char, codepoint))
                    total += 1
            except ValueError:
                # Invalid code point
                continue

    print(f"Found {total} printable glyphs", file=sys.stderr)
    return glyphs_by_category

def write_glyph_library(glyphs_by_category, filename):
    """Write organized glyph library to file"""

    category_names = {
        'Ll': 'Lowercase Letters',
        'Lu': 'Uppercase Letters',
        'Lt': 'Titlecase Letters',
        'Lm': 'Modifier Letters',
        'Lo': 'Other Letters',
        'Mn': 'Nonspacing Marks',
        'Mc': 'Spacing Marks',
        'Me': 'Enclosing Marks',
        'Nd': 'Decimal Numbers',
        'Nl': 'Letter Numbers',
        'No': 'Other Numbers',
        'Pc': 'Connector Punctuation',
        'Pd': 'Dash Punctuation',
        'Ps': 'Open Punctuation',
        'Pe': 'Close Punctuation',
        'Pi': 'Initial Punctuation',
        'Pf': 'Final Punctuation',
        'Po': 'Other Punctuation',
        'Sm': 'Math Symbols',
        'Sc': 'Currency Symbols',
        'Sk': 'Modifier Symbols',
        'So': 'Other Symbols',
    }

    with open(filename, 'w', encoding='utf-8') as f:
        f.write("# UNICODE GLYPH LIBRARY\n")
        f.write("# Generated by Unicode Glyph Harvester\n")
        f.write(f"# Total categories: {len(glyphs_by_category)}\n\n")

        # Sort categories for consistent output
        for category in sorted(glyphs_by_category.keys()):
            glyphs = glyphs_by_category[category]
            cat_name = category_names.get(category, category)

            f.write(f"\n{'='*80}\n")
            f.write(f"CATEGORY: {category} - {cat_name}\n")
            f.write(f"Count: {len(glyphs)}\n")
            f.write(f"{'='*80}\n\n")

            # Write glyphs in grid format for visual scanning
            chars_per_line = 80
            for i in range(0, len(glyphs), chars_per_line):
                chunk = glyphs[i:i+chars_per_line]
                f.write(''.join(char for char, _ in chunk))
                f.write('\n')

            # Also write with codepoints for reference
            f.write("\n# With codepoints:\n")
            for char, codepoint in glyphs[:20]:  # Just first 20 as examples
                try:
                    name = unicodedata.name(char, "UNNAMED")
                except ValueError:
                    name = "UNNAMED"
                f.write(f"U+{codepoint:04X} {char}  {name}\n")
            if len(glyphs) > 20:
                f.write(f"... and {len(glyphs) - 20} more\n")

def create_curated_sets(glyphs_by_category, filename):
    """Create hand-curated glyph sets for asciicology"""

    with open(filename, 'w', encoding='utf-8') as f:
        f.write("# CURATED GLYPH SETS FOR ASCIICOLOGY\n")
        f.write("# Python-ready lists for your experiments\n\n")

        # Box drawing characters - CRITICAL for structure
        f.write("# Box Drawing (2500-257F)\n")
        f.write("BOX_DRAWING = [\n")
        box_chars = [chr(i) for i in range(0x2500, 0x2580)
                     if is_printable_glyph(chr(i))]
        for i in range(0, len(box_chars), 16):
            chunk = box_chars[i:i+16]
            f.write(f"    '{''.join(chunk)}'\n")
        f.write("]\n\n")

        # Block elements
        f.write("# Block Elements (2580-259F)\n")
        f.write("BLOCKS = '")
        f.write(''.join(chr(i) for i in range(0x2580, 0x25A0)
                       if is_printable_glyph(chr(i))))
        f.write("'\n\n")

        # Geometric shapes
        f.write("# Geometric Shapes (25A0-25FF)\n")
        f.write("GEOMETRIC = '")
        f.write(''.join(chr(i) for i in range(0x25A0, 0x2600)
                       if is_printable_glyph(chr(i))))
        f.write("'\n\n")

        # Braille patterns - AMAZING for density gradients
        f.write("# Braille Patterns (2800-28FF) - 256 density levels!\n")
        f.write("BRAILLE = [\n")
        braille = [chr(i) for i in range(0x2800, 0x2900)]
        for i in range(0, len(braille), 32):
            chunk = braille[i:i+32]
            f.write(f"    '{''.join(chunk)}',\n")
        f.write("]\n\n")

        # Math symbols
        f.write("# Mathematical Operators (2200-22FF)\n")
        f.write("MATH_OPS = '")
        f.write(''.join(chr(i) for i in range(0x2200, 0x2300)
                       if is_printable_glyph(chr(i))))
        f.write("'\n\n")

        # Misc symbols
        f.write("# Miscellaneous Symbols (2600-26FF)\n")
        f.write("MISC_SYMBOLS = '")
        f.write(''.join(chr(i) for i in range(0x2600, 0x2700)
                       if is_printable_glyph(chr(i))))
        f.write("'\n\n")

        # Combining diacriticals - could be WILD
        if 'Mn' in glyphs_by_category:
            f.write("# Combining Diacritical Marks - overlay effects!\n")
            f.write("COMBINING = '")
            f.write(''.join(char for char, _ in glyphs_by_category['Mn'][:50]))
            f.write("'\n\n")

if __name__ == "__main__":
    print("Harvesting Unicode glyphs...", file=sys.stderr)
    glyphs = harvest_unicode_glyphs()

    print("Writing full library...", file=sys.stderr)
    write_glyph_library(glyphs, "unicode_glyphs_full.txt")

    print("Creating curated sets...", file=sys.stderr)
    create_curated_sets(glyphs, "glyph_sets.py")

    print("\nComplete!", file=sys.stderr)
    print(f"Full library: unicode_glyphs_full.txt", file=sys.stderr)
    print(f"Curated sets: glyph_sets.py", file=sys.stderr)
